// Objective-C API for talking to github.com/gfwfighter/xray-wrapper Go package.
//   gobind -lang=objc github.com/gfwfighter/xray-wrapper
//
// File is generated by gobind. Do not edit.

#ifndef __XRay_H__
#define __XRay_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class XRayInstance;
@class XRayProxyStats;
@class XRaySpeedTest;
@protocol XRayLogger;
@class XRayLogger;
@protocol XRaySpeedTestDelegate;
@class XRaySpeedTestDelegate;

@protocol XRayLogger <NSObject>
- (void)onAccessLog:(NSString* _Nullable)message;
- (void)onDNSLog:(NSString* _Nullable)message;
- (void)onGeneralMessage:(long)severity message:(NSString* _Nullable)message;
@end

@protocol XRaySpeedTestDelegate <NSObject>
- (void)gotClientInfo:(NSString* _Nullable)isp ip:(NSString* _Nullable)ip;
- (void)gotDownloadSpeed:(double)value final:(BOOL)final;
- (void)gotServerInfo:(NSString* _Nullable)name location:(NSString* _Nullable)location distance:(NSString* _Nullable)distance ping:(double)ping;
- (void)gotUploadSpeed:(double)value final:(BOOL)final;
- (void)speedTestError:(NSError* _Nullable)e;
@end

@interface XRayInstance : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)configPath assetPath:(NSString* _Nullable)assetPath logger:(id<XRayLogger> _Nullable)logger;
- (BOOL)reloadConfig:(NSError* _Nullable* _Nullable)error;
- (BOOL)start:(NSError* _Nullable* _Nullable)error;
- (BOOL)stop:(NSError* _Nullable* _Nullable)error;
@end

@interface XRayProxyStats : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t uplink;
@property (nonatomic) int64_t downlink;
@end

@interface XRaySpeedTest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(id<XRaySpeedTestDelegate> _Nullable)delegate;
- (void)start;
- (void)stop;
@end

FOUNDATION_EXPORT XRayProxyStats* _Nullable XRayGetProxyStats(NSString* _Nullable server, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT int32_t XRayGetTunnelFileDescriptor(void);

FOUNDATION_EXPORT void XRayLimitMemory(int64_t maxMemory, long refreshInterval);

FOUNDATION_EXPORT XRayInstance* _Nullable XRayNewInstance(NSString* _Nullable configPath, NSString* _Nullable assetPath, id<XRayLogger> _Nullable logger, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT XRaySpeedTest* _Nullable XRayNewSpeedTest(id<XRaySpeedTestDelegate> _Nullable delegate);

FOUNDATION_EXPORT NSString* _Nonnull XRayParseOutbound(NSString* _Nullable uri);

FOUNDATION_EXPORT BOOL XRaySwitchConfig(NSString* _Nullable server, NSString* _Nullable config, NSError* _Nullable* _Nullable error);

@class XRayLogger;

@class XRaySpeedTestDelegate;

@interface XRayLogger : NSObject <goSeqRefInterface, XRayLogger> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onAccessLog:(NSString* _Nullable)message;
- (void)onDNSLog:(NSString* _Nullable)message;
- (void)onGeneralMessage:(long)severity message:(NSString* _Nullable)message;
@end

@interface XRaySpeedTestDelegate : NSObject <goSeqRefInterface, XRaySpeedTestDelegate> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)gotClientInfo:(NSString* _Nullable)isp ip:(NSString* _Nullable)ip;
- (void)gotDownloadSpeed:(double)value final:(BOOL)final;
- (void)gotServerInfo:(NSString* _Nullable)name location:(NSString* _Nullable)location distance:(NSString* _Nullable)distance ping:(double)ping;
- (void)gotUploadSpeed:(double)value final:(BOOL)final;
- (void)speedTestError:(NSError* _Nullable)e;
@end

#endif
